language: android

machine:
java:
version: openjdk8
environment:
ANDROID_HOME: /usr/local/android-sdk-linux

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools